//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainTicketsParser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterPart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CounterPart()
        {
            this.Transporter = new Transporter();
            this.Insurer = new Insurer();
        }
    
        public System.Guid CounterPartId { get; set; }
    
        public Transporter Transporter { get; set; }
        public Insurer Insurer { get; set; }
    
        public virtual Invoice Invoices { get; set; }
    }
}
