//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainTicketsParser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public System.Guid InvoiceId { get; set; }
        public long Id { get; set; }
        public int OuterId { get; set; }
        public string SalePointName { get; set; }
        public string AspsCode { get; set; }
        public string AspsCode2 { get; set; }
        public int State { get; set; }
        public bool IsElectronic { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerPhone { get; set; }
        public int OwnerId { get; set; }
        public int BoardingPass { get; set; }
    
        public virtual Travel Travels { get; set; }
        public virtual Price Price { get; set; }
        public virtual CounterPart CounterPart { get; set; }
        public virtual SoldSeat SoldSeat { get; set; }
    }
}
