//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainTicketsParser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldSeat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoldSeat()
        {
            this.Passenger = new Passenger();
        }
    
        public System.Guid SoldSeatId { get; set; }
        public int Id { get; set; }
        public int CarId { get; set; }
        public int TosId { get; set; }
    
        public Passenger Passenger { get; set; }
    
        public virtual Price Price { get; set; }
        public virtual Invoice Invoices { get; set; }
    }
}
