//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainTicketsParser.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainTicketXmlModelContainer : DbContext
    {
        public TrainTicketXmlModelContainer()
            : base("name=TrainTicketXmlModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Travel> Travels { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<SoldSeat> SoldSeats { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<CounterPart> CounterParts { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
    }
}
