//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainTicketsParser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Travel()
        {
            this.Src = new Src();
            this.Dst = new Dst();
        }
    
        public System.Guid TravelId { get; set; }
        public System.Guid GuidIdx { get; set; }
        public Nullable<int> TransportType { get; set; }
        public Nullable<System.DateTime> DepartureDateTime { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public string Duration { get; set; }
    
        public Src Src { get; set; }
        public Dst Dst { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Trip Trips { get; set; }
    }
}
