//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainTicketsParser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.Src = new Src();
            this.Dst = new Dst();
        }
    
        public System.Guid TripId { get; set; }
        public string Id { get; set; }
        public string Transporter { get; set; }
        public string Nickame { get; set; }
        public int State { get; set; }
        public int El { get; set; }
        public int BoardingPass { get; set; }
    
        public Src Src { get; set; }
        public Dst Dst { get; set; }
    
        public virtual Travel Travel { get; set; }
    }
}
